version: "3.8"

services:
  app:
    image: hkdarealest/simple-api-go:latest
    container_name: gin_app
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

    depends_on:
      db: # Dùng object thay vì array
        condition: service_healthy
      redis: # Không cần condition cho redis
        condition: service_started
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - SERVER_PORT=${SERVER_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
    networks:
      - backend
  db:
    image: postgres:15
    container_name: go_gin_pgdb
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    healthcheck: # Thêm healthcheck
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend
  redis:
    image: redis:latest
    container_name: go_gin_redis
    restart: always
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - backend
networks:
  backend:
volumes:
  postgres_data:
