basePath: /api/v1
definitions:
  dtos.AuthLoginInput:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  dtos.AuthRegisterInput:
    properties:
      email:
        type: string
      password:
        type: string
      userName:
        type: string
    type: object
  dtos.UserResponse:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      email:
        type: string
      id:
        type: integer
      updatedAt:
        type: string
      userName:
        type: string
    type: object
  repository.Event:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      startAt:
        type: string
      updatedAt:
        type: string
    type: object
  repository.User:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      email:
        type: string
      id:
        type: integer
      password:
        type: string
      updatedAt:
        type: string
      userName:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate a user with email and password, returning access and
        refresh tokens.
      parameters:
      - description: User login details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dtos.AuthLoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: Tokens generated successfully
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid email or password
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login a user
      tags:
      - Auth
  /auth/logout:
    get:
      description: Log out the authenticated user by clearing the refresh token cookie.
      responses:
        "200":
          description: Logout successfully
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Log out user
      tags:
      - Auth
  /auth/refresh:
    get:
      description: Refresh the access token using a valid refresh token stored in
        cookies.
      produces:
      - application/json
      responses:
        "200":
          description: New access token generated successfully
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid or expired refresh token
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Refresh user access token
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user with a unique email and hashed password.
      parameters:
      - description: User registration details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dtos.AuthRegisterInput'
      produces:
      - application/json
      responses:
        "201":
          description: User registered successfully
          schema:
            $ref: '#/definitions/repository.User'
        "400":
          description: Invalid input or email already exists
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register a new user
      tags:
      - Auth
  /events:
    get:
      description: Retrieve a list of all events
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/repository.Event'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all events
      tags:
      - Events
    post:
      consumes:
      - application/json
      description: Create a new event with the provided details.
      parameters:
      - description: Event details
        in: body
        name: event
        required: true
        schema:
          $ref: '#/definitions/repository.Event'
      produces:
      - application/json
      responses:
        "201":
          description: Created event
          schema:
            $ref: '#/definitions/repository.Event'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new event
      tags:
      - Events
  /events/{id}:
    delete:
      description: Delete an existing event by its ID.
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: Event deleted
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid ID
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete an existing event
      tags:
      - Events
    get:
      consumes:
      - application/json
      description: Retrieve an event's details using its unique identifier.
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Event details
          schema:
            $ref: '#/definitions/repository.Event'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get an event by ID
      tags:
      - Events
    put:
      consumes:
      - application/json
      description: Update an existing event with the provided details.
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: integer
      - description: Event details
        in: body
        name: event
        required: true
        schema:
          $ref: '#/definitions/repository.Event'
      produces:
      - application/json
      responses:
        "200":
          description: Updated event
          schema:
            $ref: '#/definitions/repository.Event'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update an existing event
      tags:
      - Events
  /events/search:
    get:
      consumes:
      - application/json
      description: Search for events by name with pagination support
      parameters:
      - description: Event name
        in: query
        name: name
        type: string
      - description: Limit
        in: query
        name: limit
        required: true
        type: integer
      - description: Offset
        in: query
        name: offset
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Search results with pagination meta
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid request parameters
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Search events
      tags:
      - Events
  /users/my-profile:
    get:
      description: Retrieve the profile information of the authenticated user.
      produces:
      - application/json
      responses:
        "200":
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/dtos.UserResponse'
        "500":
          description: User not found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get user profile
      tags:
      - User
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
